In [6]:
import os

print(os.listdir("/content"))

['.config', 'customer_churn_sample (2).csv', 'sample_data']

In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/customer_churn_sample (2).csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (15, 11)

,CustomerID,Gender,Age,TenureMonths,SubscriptionType,MonthlyCharges,TotalCharges,ContractType,SupportTickets,PaymentMethod,Churn
0,CUST-1001,Female,34,12,Basic,49.99,599.88,Month-to-Month,3,Credit Card,Yes
1,CUST-1002,Male,45,24,Pro,79.99,1919.76,One Year,1,Bank Transfer,No
2,CUST-1003,Female,29,6,Basic,49.99,299.94,Month-to-Month,5,UPI,Yes
3,CUST-1004,Male,52,36,Enterprise,149.99,5399.64,Two Year,0,Credit Card,No
4,CUST-1005,Female,41,8,Pro,79.99,639.92,Month-to-Month,4,Debit Card,Yes

In [9]:
print("Column names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

Column names:
['CustomerID', 'Gender', 'Age', 'TenureMonths', 'SubscriptionType', 'MonthlyCharges', 'TotalCharges', 'ContractType', 'SupportTickets', 'PaymentMethod', 'Churn']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        15 non-null     object
 1   Gender            15 non-null     object
 2   Age               15 non-null     int64
 3   TenureMonths      15 non-null     int64
 4   SubscriptionType  15 non-null     object
 5   MonthlyCharges    15 non-null     float64
 6   TotalCharges      15 non-null     float64
 7   ContractType      15 non-null     object
 8   SupportTickets    15 non-null     int64
 9   PaymentMethod     15 non-null     object
 10  Churn             15 non-null     object
dtypes: float64(2), int64(3), object(6)
memory usage: 1.4+ KB

In [10]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
CustomerID          0
Gender              0
Age                 0
TenureMonths        0
SubscriptionType    0
MonthlyCharges      0
TotalCharges        0
ContractType        0
SupportTickets      0
PaymentMethod       0
Churn               0
dtype: int64

In [11]:
features = [
    "CustomerID",
    "TenureMonths",
    "MonthlyCharges",
    "TotalCharges",
    "ContractType",
    "SupportTickets",
    "Churn"
]

df[features]

,CustomerID,TenureMonths,MonthlyCharges,TotalCharges,ContractType,SupportTickets,Churn
0,CUST-1001,12,49.99,599.88,Month-to-Month,3,Yes
1,CUST-1002,24,79.99,1919.76,One Year,1,No
2,CUST-1003,6,49.99,299.94,Month-to-Month,5,Yes
3,CUST-1004,36,149.99,5399.64,Two Year,0,No
4,CUST-1005,8,79.99,639.92,Month-to-Month,4,Yes
5,CUST-1006,18,49.99,899.82,One Year,2,No
6,CUST-1007,3,49.99,149.97,Month-to-Month,6,Yes
7,CUST-1008,48,149.99,7199.52,Two Year,1,No
8,CUST-1009,15,79.99,1199.85,One Year,2,No
9,CUST-1010,4,49.99,199.96,Month-to-Month,4,Yes
10,CUST-1011,30,149.99,4499.70,Two Year,0,No
11,CUST-1012,14,79.99,1119.86,Month-to-Month,3,Yes
12,CUST-1013,22,49.99,1099.78,One Year,1,No
13,CUST-1014,2,49.99,99.98,Month-to-Month,5,Yes
14,CUST-1015,40,149.99,5999.60,Two Year,1,No

In [12]:
print("Tenure range:",
      df["TenureMonths"].min(),
      "to",
      df["TenureMonths"].max())

print("Monthly charges range:",
      df["MonthlyCharges"].min(),
      "to",
      df["MonthlyCharges"].max())

print("Total charges range:",
      df["TotalCharges"].min(),
      "to",
      df["TotalCharges"].max())

print("Support tickets range:",
      df["SupportTickets"].min(),
      "to",
      df["SupportTickets"].max())

Tenure range: 2 to 48
Monthly charges range: 49.99 to 149.99
Total charges range: 99.98 to 7199.52
Support tickets range: 0 to 6

In [13]:
print("Contract types:")
print(df["ContractType"].value_counts())

print("\nSubscription types:")
print(df["SubscriptionType"].value_counts())

print("\nPayment methods:")
print(df["PaymentMethod"].value_counts())

print("\nChurn:")
print(df["Churn"].value_counts())

Contract types:
ContractType
Month-to-Month    7
One Year          4
Two Year          4
Name: count, dtype: int64

Subscription types:
SubscriptionType
Basic         7
Pro           4
Enterprise    4
Name: count, dtype: int64

Payment methods:
PaymentMethod
Credit Card      6
UPI              4
Bank Transfer    3
Debit Card       2
Name: count, dtype: int64

Churn:
Churn
No     8
Yes    7
Name: count, dtype: int64

In [14]:
print("Median Tenure:", df["TenureMonths"].median())
print("Median Monthly Charges:", df["MonthlyCharges"].median())
print("Median Support Tickets:", df["SupportTickets"].median())

Median Tenure: 15.0
Median Monthly Charges: 79.99
Median Support Tickets: 2.0

In [15]:
def create_segment(row):
    if row["TenureMonths"] >= df["TenureMonths"].median() and row["SupportTickets"] <= df["SupportTickets"].median():
        return "Loyal & Stable"

    elif row["TenureMonths"] < df["TenureMonths"].median() and row["SupportTickets"] > df["SupportTickets"].median():
        return "New & High Support"

    elif row["TenureMonths"] < df["TenureMonths"].median():
        return "Newer Customers"

    else:
        return "Established Customers"


df["Segment"] = df.apply(create_segment, axis=1)

df[[
    "CustomerID",
    "TenureMonths",
    "MonthlyCharges",
    "SupportTickets",
    "ContractType",
    "Segment",
    "Churn"
]]

,CustomerID,TenureMonths,MonthlyCharges,SupportTickets,ContractType,Segment,Churn
0,CUST-1001,12,49.99,3,Month-to-Month,New & High Support,Yes
1,CUST-1002,24,79.99,1,One Year,Loyal & Stable,No
2,CUST-1003,6,49.99,5,Month-to-Month,New & High Support,Yes
3,CUST-1004,36,149.99,0,Two Year,Loyal & Stable,No
4,CUST-1005,8,79.99,4,Month-to-Month,New & High Support,Yes
5,CUST-1006,18,49.99,2,One Year,Loyal & Stable,No
6,CUST-1007,3,49.99,6,Month-to-Month,New & High Support,Yes
7,CUST-1008,48,149.99,1,Two Year,Loyal & Stable,No
8,CUST-1009,15,79.99,2,One Year,Loyal & Stable,No
9,CUST-1010,4,49.99,4,Month-to-Month,New & High Support,Yes
10,CUST-1011,30,149.99,0,Two Year,Loyal & Stable,No
11,CUST-1012,14,79.99,3,Month-to-Month,New & High Support,Yes
12,CUST-1013,22,49.99,1,One Year,Loyal & Stable,No
13,CUST-1014,2,49.99,5,Month-to-Month,New & High Support,Yes
14,CUST-1015,40,149.99,1,Two Year,Loyal & Stable,No

In [16]:
segment_summary = df.groupby("Segment").agg(
    Customers=("CustomerID", "count"),
    Avg_Tenure=("TenureMonths", "mean"),
    Avg_Monthly_Charges=("MonthlyCharges", "mean"),
    Avg_Support_Tickets=("SupportTickets", "mean"),
    Churned_Customers=("Churn", lambda x: (x == "Yes").sum())
).reset_index()

segment_summary

,Segment,Customers,Avg_Tenure,Avg_Monthly_Charges,Avg_Support_Tickets,Churned_Customers
0,Loyal & Stable,8,29.125,107.490000,1.000000,0
1,New & High Support,7,7.000,58.561429,4.285714,7

In [17]:
segment_summary["Churn_Rate"] = (
    segment_summary["Churned_Customers"]
    / segment_summary["Customers"]
    * 100
).round(1)

segment_summary

,Segment,Customers,Avg_Tenure,Avg_Monthly_Charges,Avg_Support_Tickets,Churned_Customers,Churn_Rate
0,Loyal & Stable,8,29.125,107.490000,1.000000,0,0.0
1,New & High Support,7,7.000,58.561429,4.285714,7,100.0

In [18]:
tenure_median = df["TenureMonths"].median()
tickets_median = df["SupportTickets"].median()

df["Risk_Tenure"] = np.where(
    df["TenureMonths"] < tenure_median, 2, 0
)

df["Risk_Contract"] = np.where(
    df["ContractType"] == "Month-to-Month", 2, 0
)

df["Risk_Support"] = np.where(
    df["SupportTickets"] > tickets_median, 1, 0
)

df["Churn_Risk_Score"] = (
    df["Risk_Tenure"]
    + df["Risk_Contract"]
    + df["Risk_Support"]
)

df[[
    "CustomerID",
    "TenureMonths",
    "ContractType",
    "SupportTickets",
    "Risk_Tenure",
    "Risk_Contract",
    "Risk_Support",
    "Churn_Risk_Score",
    "Churn"
]]

,CustomerID,TenureMonths,ContractType,SupportTickets,Risk_Tenure,Risk_Contract,Risk_Support,Churn_Risk_Score,Churn
0,CUST-1001,12,Month-to-Month,3,2,2,1,5,Yes
1,CUST-1002,24,One Year,1,0,0,0,0,No
2,CUST-1003,6,Month-to-Month,5,2,2,1,5,Yes
3,CUST-1004,36,Two Year,0,0,0,0,0,No
4,CUST-1005,8,Month-to-Month,4,2,2,1,5,Yes
5,CUST-1006,18,One Year,2,0,0,0,0,No
6,CUST-1007,3,Month-to-Month,6,2,2,1,5,Yes
7,CUST-1008,48,Two Year,1,0,0,0,0,No
8,CUST-1009,15,One Year,2,0,0,0,0,No
9,CUST-1010,4,Month-to-Month,4,2,2,1,5,Yes
10,CUST-1011,30,Two Year,0,0,0,0,0,No
11,CUST-1012,14,Month-to-Month,3,2,2,1,5,Yes
12,CUST-1013,22,One Year,1,0,0,0,0,No
13,CUST-1014,2,Month-to-Month,5,2,2,1,5,Yes
14,CUST-1015,40,Two Year,1,0,0,0,0,No

In [19]:
def risk_level(score):
    if score >= 4:
        return "High Risk"
    elif score >= 2:
        return "Medium Risk"
    else:
        return "Low Risk"

df["Risk_Level"] = df["Churn_Risk_Score"].apply(risk_level)

df[[
    "CustomerID",
    "Churn_Risk_Score",
    "Risk_Level",
    "Churn"
]]

   CustomerID  Churn_Risk_Score Risk_Level Churn
0   CUST-1001                 5  High Risk   Yes
1   CUST-1002                 0   Low Risk    No
2   CUST-1003                 5  High Risk   Yes
3   CUST-1004                 0   Low Risk    No
4   CUST-1005                 5  High Risk   Yes
5   CUST-1006                 0   Low Risk    No
6   CUST-1007                 5  High Risk   Yes
7   CUST-1008                 0   Low Risk    No
8   CUST-1009                 0   Low Risk    No
9   CUST-1010                 5  High Risk   Yes
10  CUST-1011                 0   Low Risk    No
11  CUST-1012                 5  High Risk   Yes
12  CUST-1013                 0   Low Risk    No
13  CUST-1014                 5  High Risk   Yes
14  CUST-1015                 0   Low Risk    No

In [20]:
risk_summary = df.groupby("Risk_Level").agg(
    Customers=("CustomerID", "count"),
    Avg_Risk_Score=("Churn_Risk_Score", "mean"),
    Churned_Customers=("Churn", lambda x: (x == "Yes").sum())
).reset_index()

risk_summary

  Risk_Level  Customers  Avg_Risk_Score  Churned_Customers
0  High Risk          7             5.0                  7
1   Low Risk          8             0.0                  0

In [21]:
final_customer_table = df[[
    "CustomerID",
    "TenureMonths",
    "MonthlyCharges",
    "TotalCharges",
    "ContractType",
    "SupportTickets",
    "Segment",
    "Churn_Risk_Score",
    "Risk_Level",
    "Churn"
]].copy()

final_customer_table

,CustomerID,TenureMonths,MonthlyCharges,TotalCharges,ContractType,SupportTickets,Segment,Churn_Risk_Score,Risk_Level,Churn
0,CUST-1001,12,49.99,599.88,Month-to-Month,3,New & High Support,5,High Risk,Yes
1,CUST-1002,24,79.99,1919.76,One Year,1,Loyal & Stable,0,Low Risk,No
2,CUST-1003,6,49.99,299.94,Month-to-Month,5,New & High Support,5,High Risk,Yes
3,CUST-1004,36,149.99,5399.64,Two Year,0,Loyal & Stable,0,Low Risk,No
4,CUST-1005,8,79.99,639.92,Month-to-Month,4,New & High Support,5,High Risk,Yes
5,CUST-1006,18,49.99,899.82,One Year,2,Loyal & Stable,0,Low Risk,No
6,CUST-1007,3,49.99,149.97,Month-to-Month,6,New & High Support,5,High Risk,Yes
7,CUST-1008,48,149.99,7199.52,Two Year,1,Loyal & Stable,0,Low Risk,No
8,CUST-1009,15,79.99,1199.85,One Year,2,Loyal & Stable,0,Low Risk,No
9,CUST-1010,4,49.99,199.96,Month-to-Month,4,New & High Support,5,High Risk,Yes
10,CUST-1011,30,149.99,4499.70,Two Year,0,Loyal & Stable,0,Low Risk,No
11,CUST-1012,14,79.99,1119.86,Month-to-Month,3,New & High Support,5,High Risk,Yes
12,CUST-1013,22,49.99,1099.78,One Year,1,Loyal & Stable,0,Low Risk,No
13,CUST-1014,2,49.99,99.98,Month-to-Month,5,New & High Support,5,High Risk,Yes
14,CUST-1015,40,149.99,5999.60,Two Year,1,Loyal & Stable,0,Low Risk,No

In [22]:
print("Possible risk scores:")
print(sorted(df["Churn_Risk_Score"].unique()))

print("\nMinimum score:", df["Churn_Risk_Score"].min())
print("Maximum score:", df["Churn_Risk_Score"].max())

Possible risk scores:
[np.int64(0), np.int64(5)]

Minimum score: 0
Maximum score: 5

In [23]:
print(df["Risk_Level"].value_counts())

print("\nMissing risk levels:")
print(df["Risk_Level"].isnull().sum())

Risk_Level
Low Risk     8
High Risk    7
Name: count, dtype: int64

Missing risk levels:
0

In [24]:
print(
    df[["TenureMonths", "Risk_Tenure"]]
    .sort_values("TenureMonths")
)

    TenureMonths  Risk_Tenure
13             2            2
6              3            2
9              4            2
2              6            2
4              8            2
0             12            2
11            14            2
8             15            0
5             18            0
12            22            0
1             24            0
10            30            0
3             36            0
14            40            0
7             48            0

In [25]:
print(
    df[["ContractType", "Risk_Contract"]]
    .drop_duplicates()
)

     ContractType  Risk_Contract
0  Month-to-Month              2
1        One Year              0
3        Two Year              0

In [26]:
print(
    df[["SupportTickets", "Risk_Support"]]
    .sort_values("SupportTickets")
)

    SupportTickets  Risk_Support
3                0             0
10               0             0
7                1             0
1                1             0
12               1             0
14               1             0
8                2             0
5                2             0
11               3             1
0                3             1
4                4             1
9                4             1
13               5             1
2                5             1
6                6             1

In [27]:
final_customer_table.to_csv(
    "customer_segment_risk_table.csv",
    index=False
)

print("File created successfully!")

File created successfully!

In [28]:
final_customer_table.head(15)

,CustomerID,TenureMonths,MonthlyCharges,TotalCharges,ContractType,SupportTickets,Segment,Churn_Risk_Score,Risk_Level,Churn
0,CUST-1001,12,49.99,599.88,Month-to-Month,3,New & High Support,5,High Risk,Yes
1,CUST-1002,24,79.99,1919.76,One Year,1,Loyal & Stable,0,Low Risk,No
2,CUST-1003,6,49.99,299.94,Month-to-Month,5,New & High Support,5,High Risk,Yes
3,CUST-1004,36,149.99,5399.64,Two Year,0,Loyal & Stable,0,Low Risk,No
4,CUST-1005,8,79.99,639.92,Month-to-Month,4,New & High Support,5,High Risk,Yes
5,CUST-1006,18,49.99,899.82,One Year,2,Loyal & Stable,0,Low Risk,No
6,CUST-1007,3,49.99,149.97,Month-to-Month,6,New & High Support,5,High Risk,Yes
7,CUST-1008,48,149.99,7199.52,Two Year,1,Loyal & Stable,0,Low Risk,No
8,CUST-1009,15,79.99,1199.85,One Year,2,Loyal & Stable,0,Low Risk,No
9,CUST-1010,4,49.99,199.96,Month-to-Month,4,New & High Support,5,High Risk,Yes
10,CUST-1011,30,149.99,4499.70,Two Year,0,Loyal & Stable,0,Low Risk,No
11,CUST-1012,14,79.99,1119.86,Month-to-Month,3,New & High Support,5,High Risk,Yes
12,CUST-1013,22,49.99,1099.78,One Year,1,Loyal & Stable,0,Low Risk,No
13,CUST-1014,2,49.99,99.98,Month-to-Month,5,New & High Support,5,High Risk,Yes
14,CUST-1015,40,149.99,5999.60,Two Year,1,Loyal & Stable,0,Low Risk,No

In [29]:
final_customer_table.head(15)

,CustomerID,TenureMonths,MonthlyCharges,TotalCharges,ContractType,SupportTickets,Segment,Churn_Risk_Score,Risk_Level,Churn
0,CUST-1001,12,49.99,599.88,Month-to-Month,3,New & High Support,5,High Risk,Yes
1,CUST-1002,24,79.99,1919.76,One Year,1,Loyal & Stable,0,Low Risk,No
2,CUST-1003,6,49.99,299.94,Month-to-Month,5,New & High Support,5,High Risk,Yes
3,CUST-1004,36,149.99,5399.64,Two Year,0,Loyal & Stable,0,Low Risk,No
4,CUST-1005,8,79.99,639.92,Month-to-Month,4,New & High Support,5,High Risk,Yes
5,CUST-1006,18,49.99,899.82,One Year,2,Loyal & Stable,0,Low Risk,No
6,CUST-1007,3,49.99,149.97,Month-to-Month,6,New & High Support,5,High Risk,Yes
7,CUST-1008,48,149.99,7199.52,Two Year,1,Loyal & Stable,0,Low Risk,No
8,CUST-1009,15,79.99,1199.85,One Year,2,Loyal & Stable,0,Low Risk,No
9,CUST-1010,4,49.99,199.96,Month-to-Month,4,New & High Support,5,High Risk,Yes
10,CUST-1011,30,149.99,4499.70,Two Year,0,Loyal & Stable,0,Low Risk,No
11,CUST-1012,14,79.99,1119.86,Month-to-Month,3,New & High Support,5,High Risk,Yes
12,CUST-1013,22,49.99,1099.78,One Year,1,Loyal & Stable,0,Low Risk,No
13,CUST-1014,2,49.99,99.98,Month-to-Month,5,New & High Support,5,High Risk,Yes
14,CUST-1015,40,149.99,5999.60,Two Year,1,Loyal & Stable,0,Low Risk,No

In [30]:
recommendation_summary = df.groupby("Risk_Level").agg(
    Customers=("CustomerID", "count"),
    Avg_Monthly_Charges=("MonthlyCharges", "mean"),
    Avg_Tenure=("TenureMonths", "mean"),
    Avg_Support_Tickets=("SupportTickets", "mean"),
    Observed_Churn=("Churn", lambda x: (x == "Yes").sum())
).reset_index()

recommendation_summary

,Risk_Level,Customers,Avg_Monthly_Charges,Avg_Tenure,Avg_Support_Tickets,Observed_Churn
0,High Risk,7,58.561429,7.000,4.285714,7
1,Low Risk,8,107.490000,29.125,1.000000,0

In [31]:
recommendation_summary["Observed_Churn_Rate"] = (
    recommendation_summary["Observed_Churn"]
    / recommendation_summary["Customers"]
    * 100
).round(1)

recommendation_summary

,Risk_Level,Customers,Avg_Monthly_Charges,Avg_Tenure,Avg_Support_Tickets,Observed_Churn,Observed_Churn_Rate
0,High Risk,7,58.561429,7.000,4.285714,7,100.0
1,Low Risk,8,107.490000,29.125,1.000000,0,0.0

# Customer Segmentation and Churn-Risk Recommendation Memo

## Objective

The objective of this analysis is to segment customers based on account and behavioral characteristics and create a transparent, rule-based churn-risk score that can be used to prioritize customer-retention actions.

## Segmentation Approach

Customers were segmented using tenure and support-ticket activity. The approach uses simple, reproducible rules so that each segment can be easily understood and explained.

The segments are:

* **Loyal & Stable:** Longer-tenure customers with relatively fewer support tickets.
* **New & High Support:** Newer customers with relatively higher support activity.
* **Newer Customers:** Customers with shorter tenure who may require additional engagement.
* **Established Customers:** Longer-tenure customers who do not fall into the stable segment.

## Churn-Risk Scoring

A rule-based score from 0 to 5 was created using three observable signals:

* Short tenure: +2 points
* Month-to-month contract: +2 points
* Higher-than-median support tickets: +1 point

Risk levels were assigned as:

* **0–1:** Low Risk
* **2–3:** Medium Risk
* **4–5:** High Risk

The score is intentionally transparent so that a business user can understand why a customer received a particular risk level.

## Recommendations

Customers classified as higher risk can be prioritized for retention review. For customers with short tenure and high support activity, the business can consider onboarding assistance and proactive support. Customers on month-to-month contracts can be considered for appropriate engagement or contract-retention initiatives.

Lower-risk customers can continue through regular customer-success activities rather than receiving the same level of intervention.

## Validation

The model was checked for missing risk levels, valid score ranges, and correct application of the individual scoring rules. The dataset contained no missing values, and the scoring logic was applied consistently across the customer records.

Observed churn was used only for validation and interpretation; it was not used as an input to calculate the risk score.

## Limitations

This analysis uses a small sample of 15 customers, so the results should not be generalized to a larger customer population without additional data. The risk score is a prioritization tool rather than a prediction of whether an individual customer will churn.

Further validation on a larger historical dataset would be required before using the score for automated customer decisions.

# Final Project Summary

This project developed an explainable customer segmentation and churn-risk prioritization model using customer account and behavioral data.

Customers were segmented using tenure and support-ticket activity. A transparent churn-risk score was created using short tenure, month-to-month contracts, and higher-than-median support activity as risk signals.

The model provides a simple way to prioritize customers for retention review while keeping the reasoning behind each score understandable to business users.

The analysis also included validation of score ranges, risk-level assignment, and edge cases. Observed churn was used for validation rather than as an input to the risk score.

Because the dataset contains only 15 customers, the results are intended for demonstration and decision-support purposes. A larger historical dataset would be required for stronger validation and production use.